export const ADD_TO_CART = "ADD_TO_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOGGLE_AMOUNT_OF_COPIES = "TOGGLE_AMOUNT_OF_COPIES";
